Repository wanted-internship-11th-team10/pre-onboarding-11th-3-10, pull requests merged in 2023-07, with the labels that each got.

#11 feat : 로딩 UI 구현 및 적용
  src/components/Issue.tsx
  src/components/IssueList.tsx
  src/components/common/Loading.tsx
  src/routes.tsx
Labels: enhancement

#13 release : v1.0.0 - github issues 작성
  .env.example
  index.html
  package-lock.json
  package.json
  public/logo.svg
  src/App.tsx
  src/Global.tsx
  src/api/index.ts
  src/api/issue.ts
  src/assets/ad.jpeg
  src/components/Advertise.tsx
  src/components/Issue.tsx
  src/components/IssueBanner.tsx
  src/components/IssueList.tsx
  src/components/Issues.tsx
  src/components/common/Loading.tsx
  src/context/IssueContext.tsx
  src/context/IssueProvider.tsx
  src/context/useIssueContext.tsx
  src/hook/index.ts
  src/hook/useFetchIssue.tsx
  src/hook/useFetchIssues.tsx
  src/hook/useInfiniteScroll.tsx
  src/index.css
  src/main.tsx
  src/pages/ErrorPage.tsx
  src/pages/IssuePage.tsx
  src/routes.tsx
  src/style/markdown-styles.module.css
  src/utils/cache.ts
  src/utils/index.ts
  src/utils/wrapPromise.ts
  tsconfig.json
Labels: 🚀 release

#14 refactor : 패키지 삭제 및 기타 사항 수정
  package-lock.json
  package.json
  src/components/Issue.tsx
  src/components/IssueBanner.tsx
  src/components/common/ScrollTop.tsx
  src/pages/ErrorPage.tsx
Labels: bug, enhancement

#15 release : v1.1.0
  package-lock.json
  package.json
  src/components/Issue.tsx
  src/components/IssueBanner.tsx
  src/components/common/ScrollTop.tsx
  src/pages/ErrorPage.tsx
Labels: 🚀 release
